### ISSUE TITLE
[Bug] Word meaning is always pouch's

### ISSUE THREAD

**Issue by HeySreelal** [HeySreelal/xwordle#20]
word meaning is always retrieved form the `day.json`

**Comment by HeySreelal** [comment]
💀 type 'Null' is not a subtype of type 'Map<String, dynamic>'
```
#0      new Phonetic.fromJson (package:xwordle/services/dict.dart:114:37)
#1      new Word.fromJson.<anonymous closure> (package:xwordle/services/dict.dart:55:27)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      new List.from (dart:core-patch/array_patch.dart:37:17)
#5      new Word.fromJson (package:xwordle/services/dict.dart:53:18)
#6      Dictionary.getWord (package:xwordle/services/dict.dart:22:17)
<asynchronous suspension>
#7      meaningHandler.<anonymous closure> (package:xwordle/handlers/meaning.dart:24:17)
<asynchronous suspension>
#8      Televerse._onUpdate (package:televerse/src/televerse/televerse.dart:218:13)
<asynchronous suspension>
```
